name: API-LIVROS-CI-CD

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/README.md'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: api-livros
  CONTAINER_NAME: api-task
  ECS_CLUSTER: api-cluster
  ECS_SERVICE: api-service
  CODEDEPLOY_APP: api-livros-codedeploy
  CODEDEPLOY_GROUP: api-livros-deployment-group

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install ruff

      - name: Lint with ruff
        run: |
          ruff check --select=E9,F63,F7,F82 --target-version=py37 .
          ruff check --target-version=py37 .

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image_encrypted: ${{ steps.build-image.outputs.image_encrypted }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          JOB_ID: ${{ github.run_number }}
          SECRET: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
        run: |
          docker build -t $ECR_REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG $ECR_REGISTRY/${ECR_REPOSITORY}:$JOB_ID
          docker push $ECR_REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${ECR_REPOSITORY}:$JOB_ID
          image="$ECR_REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG"
          echo "::add-mask::$image"
          image_encrypted=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$image") | base64 -w0)
          echo "image_encrypted=$image_encrypted" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.CONTAINER_NAME }} \
            --query taskDefinition > task-definition.json

      - name: Get image
        id: get_image
        shell: bash
        run: |
          image_deployment=$(gpg --decrypt --quiet --batch --passphrase "$SECRET" --output - <(echo "${{ needs.build.outputs.image_encrypted }}" | base64 --decode))
          echo "::add-mask::$image_deployment"
          echo "image_deployment=$image_deployment" >> $GITHUB_OUTPUT
        env:
          SECRET: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.get_image.outputs.image_deployment }}

      - name: Register new task definition
        id: register_task_def
        run: |
          new_task_def_arn=$(aws ecs register-task-definition \
            --cli-input-json file://${{ steps.task-def.outputs.task-definition }} \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "task_def_arn=$new_task_def_arn" >> $GITHUB_OUTPUT

      - name: Update AppSpec file with new Task Definition ARN and Container Name
        run: |
          sed -i 's|<TASK_DEFINITION_ARN>|${{ steps.register_task_def.outputs.task_def_arn }}|g' appspec.yaml
          sed -i 's|<CONTAINER_NAME>|${{ env.CONTAINER_NAME }}|g' appspec.yaml
          
      - name: Show AppSpec file
        run: cat appspec.yaml

      - name: Deploy to ECS with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --revision revisionType=Local,fileExistsBehavior=OVERWRITE,fileName=appspec.yaml